### ISSUE TITLE
Quiz CSS is broken

### ISSUE THREAD

**Issue by jontanxy** [ivorymash/marshall-at-home#17]
The answer input is outside of the card.

**Comment by jasper-teng** [comment]
wtf

**Comment by jontanxy** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67737040/129204671-50bdc823-3844-4efa-826e-f93014be856a.png">

**Comment by jasper-teng** [comment]
![image](https://user-images.githubusercontent.com/38351405/129205364-55059e7a-73b8-4f0d-b72b-9aff9b5c9e8f.png)
looks fine to me?

**Comment by jontanxy** [comment]
i think i know why. my screen is smaller. yours is a monitor right? im viewing on laptop

**Comment by jasper-teng** [comment]
prfobably, if so then this is a non-issue

**Comment by jontanxy** [comment]
ok
